TRAIN_VOCAB_EN: data/train_vocab_en.txt
TRAIN_VOCAB_ZH: data/train_vocab_zh.txt
RESULT_DIR: results/
LOG_DIR: logs/
CHK_DIR: checkpoints/
DATA_DIR: data/
MAX_INPUT_LENGTH: 40
MAX_VID_LENGTH: 32
batch_size: 512
wordembed_dim: 512
enc_hid_size: 512
dec_hid_size: 1024
teacher_ratio: 1
decoder_lr: 0.001
encoder_lr: 0.001
weight_decay: 0.00005
grad_clip: 10.0
epochs: 50
seed: 123
model_type: s2s
train_id: en2zh